name: TEAM3 CI

on:
  push:

jobs:
  ci:

    env:
      DB_DATABASE: TEAM3
      DB_USER: root
      DB_PASSWORD: 2349


    runs-on: ubuntu-latest
    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Set timezone to KST
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime


      - name: Start MYSQL
        run: |
          sudo systemctl start mysql
          mysql -e "use mysql; FLUSH PRIVILEGES; ALTER USER '${{ env.DB_USER }}'@'localhost' IDENTIFIED BY '${{ env.DB_PASSWORD }}';" -uroot -proot
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-python: 3.9.9

      - run: pip install -r requirements.txt
      - run: python manage.py makemigrations
      - run: python manage.py migrate
      - run: python manage.py test